module.exports = {
  A: 'A',
  B: 'B',
  A_PLUS: 'A+',
  B_PLUS: 'B+',
  B_2: '2B',
  ALPHA: 'Alpha',
  CM_1: 'CM1',
  B_3: '3B',
  ZERO: 'Zero',
  CM_3: 'CM3',
  ZERO_W: 'Zero W',
  B_3_PLUS: '3B+',
  A_3_PLUS: '3A+',
  CM_3_PLUS: 'CM3+',
};
